// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:861523892918:web:f04772fe551c9d1a02a417',
    messagingSenderId: '861523892918',
    projectId: 'exam-hall-finder',
    authDomain: 'exam-hall-finder.firebaseapp.com',
    storageBucket: 'exam-hall-finder.firebasestorage.app',
    measurementId: 'G-SPYN3Q2CTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:861523892918:android:6e0cac5cdcd7f7e302a417',
    messagingSenderId: '861523892918',
    projectId: 'exam-hall-finder',
    storageBucket: 'exam-hall-finder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:861523892918:ios:ae0bc3237bec8bb802a417',
    messagingSenderId: '861523892918',
    projectId: 'exam-hall-finder',
    storageBucket: 'exam-hall-finder.firebasestorage.app',
    iosBundleId: 'com.example.demmyProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:861523892918:ios:ae0bc3237bec8bb802a417',
    messagingSenderId: '861523892918',
    projectId: 'exam-hall-finder',
    storageBucket: 'exam-hall-finder.firebasestorage.app',
    iosBundleId: 'com.example.demmyProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:861523892918:web:ffaacaaf62fb855402a417',
    messagingSenderId: '861523892918',
    projectId: 'exam-hall-finder',
    authDomain: 'exam-hall-finder.firebaseapp.com',
    storageBucket: 'exam-hall-finder.firebasestorage.app',
    measurementId: 'G-CJYJPQD1GL',
  );
}
